id: A393F9BD4
title: 'The Healing Medicine of Faith: A Prayer to the Lineage of the Peaceful Sādhana
  of Mañjuśrī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.855882
  last_modified_at: 2022-03-01 04:37:17.855885
