id: A393F9BD4
title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.835830
  last_modified_at: 2022-03-01 04:37:17.835833
