id: A393F9BD4
title: Prayer to Bhagavān Mañjughoṣa
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.839348
  last_modified_at: 2022-03-01 04:37:17.839350
