id: A393F9BD4
title: Light from the Wisdom Sun
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.838062
  last_modified_at: 2022-03-01 04:37:17.838065
