id: A393F9BD4
title: Prayer to the Lion of Speech
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.842297
  last_modified_at: 2022-03-01 04:37:17.842300
