id: A393F9BD4
title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra ''Chanting
  the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.863235
  last_modified_at: 2022-03-01 04:37:17.863237
