id: A393F9BD4
title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.833786
  last_modified_at: 2022-03-01 04:37:17.833790
