id: A393F9BD4
title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration towards
  the Meaning of the Indivisible Ground, Path and Fruition of the Great Perfection
  Mañjuśrī'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.847871
  last_modified_at: 2022-03-01 04:37:17.847875
