id: A393F9BD4
title: Prayer to Mañjuśrī
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.840719
  last_modified_at: 2022-03-01 04:37:17.840722
