id: A393F9BD4
title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the Profound
  Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.830187
  last_modified_at: 2022-03-01 04:37:17.830193
