id: A393F9BD4
title: 'The Torch of Wisdom: A Method of Offering Butter Lamps Based on Ārya Mañjuśrī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:37:17.861880
  last_modified_at: 2022-03-01 04:37:17.861883
